name: Android Debug APK

on:
  workflow_dispatch:   # 允許手動觸發
  push:                # 或者有推送時觸發
    paths:
      - 'app/**'
      - '.github/workflows/android.yml'
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle/**'
      - 'gradlew*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
